name: Run test cases

on: [push, pull_request]

jobs:

  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        brew install curl zip unzip gnu-sed erlang openssl@1.1
        echo "/usr/local/bin:$PATH" >> ~/.bashrc
    - name: install rebar3
      run: |
        curl -fsSL -o /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
        chmod +x /usr/local/bin/rebar3
        echo "/usr/local/bin:$PATH" >> ~/.bashrc
    - name: run eunit
      run: |
        rebar3 eunit

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        builder:
          - 5.2-7
        otp:
          - 26.1.2-1
        elixir:
          - 1.15.7
        arch:
          - amd64
          - arm64
        os:
          - ubuntu22.04
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - debian11
          - debian10
          - debian9
          - el9
          - el8
          - el7
          - amzn2

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.arch }}
    - name: run eunit
      run: |
        IMAGE=ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
        docker run --rm -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} $IMAGE bash -euc 'make eunit'
